### ISSUE TITLE
Instructions on running

### ISSUE THREAD

**Issue by JemarJones** [XanderStrike/FoosBot#1]
Having trouble figuring out how to even run this project. After installing everything and just trying `ruby bot.rb` i get 

``` ruby
Sent: Initialized! Type `!foos` to start a game!
Error: undefined method `empty?' for nil:NilClass
Error: undefined method `empty?' for nil:NilClass
Error: undefined method `empty?' for nil:NilClass
^Cbot.rb:291:in `sleep': Interrupt
    from bot.rb:291:in `<main>'
```

Is this not how you run the bot?

**Comment by XanderStrike** [comment]
Oh man sorry to say this project is dead. It's been superseded in our office by https://github.com/choruk/foos_portal. It's got a web UI and ELO player rankings.

I'll make a note on the repo.
